---

# Node exporter defaults
node_exporter_port: 9100

# Prometheus global timing defaults
prometheus_scrape_interval: "30s"
prometheus_evaluation_interval: "30s"

# Loki â€“ where promtail will send logs
# You can use mon1 hostname if DNS works, or IP
loki_url: "http://mon1:3100"

# Default system log paths to ship with promtail on Rocky/EL
promtail_log_paths:
  - /var/log/messages
  - /var/log/secure
  - /var/log/cron
  - /var/log/audit/audit.log

# Common labels to attach to metrics/logs (can be used in templates)
common_prometheus_labels:
  env: "{{ monitoring_env }}"

