- name: ensure dependencies for unarchive
  package:
    name:
      - tar
      - gzip
    state: present
- name: download and unarchive prometheus
  run_once: true
  unarchive:
    src: "{{ node_exporter_download_url }}"
    dest: "{{ node_exporter_tmp_dir }}" 
    remote_src: true
- name: create node_exporter group
  group:
    name: "{{ node_exporter_group }}"
    state: present
- name: create node_exporter user
  user:
    name: "{{ node_exporter_user }}"
    shell: /usr/bin/false
    group: "{{ node_exporter_group }}"
    create_home: false
    system: true
- name: copy executable
  copy:
    src: "{{ node_exporter_tmp_dir }}/node_exporter-{{ node_exporter_version }}.(( node_exporter_arch }}/node_exporter"
    dest: "{{ node_exporter_bin_dir }}"
    owner: "{{ node_exporter_user }}"
    group: "{{ node_exporter_group }}"
    mode: '0755'
    remote_src: true
- name: run service template
  template:
    src: node_exporter.j2
    dest: /etc/systemd/system/node_exporter.service
    owner: root
    group: root
    mode: '0644'
- name: selinux port open 9100 with http_port_t type
  seport:
    ports: 9100
    proto: tcp
    setype: http_port_t
    state: present
- name: open port 9100 in firewalld
  firewalld:
    port: 9100/tcp
    permanent: true
    state: enabled
- name: restart firewalld
  service:
    name: firewalld
    state: restarted
- name: reload systemd
  shell: 'systemctl daemon-reload'
- name: start and enable node-exporter
  service:
    name: node_exporter
    state: restarted
    enabled: true
