---
- name: ensure dependencies for unarchive
  package:
    name:
      - tar
      - gzip
    state: present
- name: download and unarchive prometheus
  run_once: true
  unarchive:
    src: "{{ prometheus_download_url }}"
    dest: "{{ prometheus_tmp_dir }}"
    remote_src: true

- name: create prometheus group
  group:
    name: "{{ prometheus_group }}"
    state: present

- name: create prometheus user
  user:
    name: "{{ prometheus_user }}"
    shell: /usr/bin/false
    group: "{{ prometheus_group }}"
    create_home: false
    system: true

- name: copy prometheus executables
  copy:
    src: "{{ prometheus_tmp_dir }}/prometheus-{{ prometheus_version }}.{{ prometheus_arch }}/{{ item }}"
    dest: "{{ prometheus_bin_dir }}/{{ item }}"
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_group }}"
    mode: '0755'
    remote_src: true
  loop:
    - prometheus
    - promtool

- name: create prometheus directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_group }}"
  loop:
    - "{{ prometheus_config_dir }}"
    - "{{ prometheus_data_dir }}"

- name: deploy prometheus systemd service unit
  template:
    src: prometheus_service.j2
    dest: /etc/systemd/system/prometheus.service
    owner: root
    group: root
    mode: '0644'

- name: deploy prometheus main config
  template:
    src: prometheus_config.j2
    dest: "{{ prometheus_config_dir }}/prometheus.yml"
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_group }}"
    mode: '0644'

- name: allow prometheus web port in SELinux
  seport:
    ports: "{{ prometheus_web_port }}"
    proto: tcp
    setype: http_port_t
    state: present

- name: open prometheus web port in firewalld
  firewalld:
    port: "{{ prometheus_web_port }}/tcp"
    permanent: true
    state: enabled
    immediate: true

- name: restart firewalld
  service:
    name: firewalld
    state: restarted

- name: reload systemd daemon
  command: systemctl daemon-reload

- name: enable and restart prometheus service
  service:
    name: prometheus
    state: restarted
    enabled: true

